name: github pages

on:
  push:
    branches:
      - docs

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # caching pip dependencies

      - name: Install Pip Requirements 🐷
        run: pip install -r requirements.txt

      - name: Build website 🛠
        shell: bash
        run: mkdocs build

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
