name: github pages

on:
  push:
    branches:
      - docs

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: libigl-website
          environment-file: libigl-website.yml
          auto-activate-base: false

      - name: Build website
        run: mkdocs build

      - name: Deploy to GitHub Pages
        if: github.repository == 'libigl/libigl.github.io'
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./site
          SCRIPT_MODE: true
        run: |
          wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.5.0/entrypoint.sh
          bash ./entrypoint.sh
