name: github pages

on:
  push:
    branches:
      - docs

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: libigl-website
          environment-file: conda.yml
          auto-activate-base: false

      - name: Build website
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda activate libigl-website
          mkdocs build

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
